#!/bin/bash
#
# GridMap
#
# created: 04.02.2014
# by zinke
#

Usage() {
cat << EOF

    Usage: $0 <> [options]

    OPTIONS:
            -

            ###########################################################
            ##   (c) wolf zinke (2014) - part of the MaFIA toolbox   ##
            ##         > MAcaque Functional Image Analysis <         ##
            ##            Licensed under the MIT license             ##
            ###########################################################


EOF
exit 1

}
 

if [ $# -lt 1 ]; then
    Usage
else
    arg1=$1;
    shift
fi
 
#__________________________________________________________________________________________#

while [ $# -gt 0 ] ;
do
    case $1 in
           -)
                shift
                ;;
          -*)   echo "Wrong option: <$1>"
                echo ""
                Usage
                ;;
           *)   break
                ;;
    esac
done

#__________________________________________________________________________________________#
 
